### ISSUE TITLE
postcss-discard: postcss.plugin was deprecated.

### ISSUE THREAD

**Issue by Lennso** [nystudio107/rollup-plugin-critical#2]
### Describe the bug
I use your great vite buildchain for craft. if i want to "make build" i got this error:
`
postcss-discard: postcss.plugin was deprecated. Migration guide:
vite_1        | https://evilmartians.com/chronicles/postcss-8-plugin-migration
`

### Expected behaviour
I think it has something to do with this plugin an the critical version? maybe it should use critical version 4?

### Versions
- Plugin version: newest

**Comment by khalwat** [comment]
Released as 1.0.8 -> https://github.com/nystudio107/rollup-plugin-critical/releases/tag/1.0.8
