### ISSUE TITLE
How to inline CSS?

### ISSUE THREAD

**Issue by muuvmuuv** [nystudio107/rollup-plugin-critical#4]
### Is your feature request related to a problem? Please describe.

I want the CSS to be included in the HTML inline but `inline: true` does not work with Vite.

### Describe the solution you would like
A clear and concise description of what you would like to have happen.

### Describe alternatives you have considered
A clear and concise description of any alternative solutions or features you have considered.

### Additional context

```js
import vue from "@vitejs/plugin-vue"
import path from "path"
import critical from "rollup-plugin-critical"
import { defineConfig } from "vite"
import { chunkSplitPlugin } from "vite-plugin-chunk-split"
import { ViteCspPlugin } from "vite-plugin-csp"
import { createHtmlPlugin } from "vite-plugin-html"
import viteImagemin from "vite-plugin-imagemin"

import { version } from "./package.json"

export default defineConfig({
  plugins: [
    vue(),
    viteImagemin(),
    chunkSplitPlugin({
      customSplitting: {
        fortawesome: [/@fortawesome\/.*/],
        fontsource: [/@fontsource\/.*/],
      },
    }),
    ViteCspPlugin({
      onDev: "full",
    }),
    createHtmlPlugin({
      minify: process.env.NODE_ENV === "production",
    }),
    critical({
      criticalUrl: "xxxxxxx",
      criticalBase: "dist",
      criticalPages: [{ uri: "", template: "index" }],
      criticalConfig: {
        strict: true,
        inline: true,
      },
    }),
  ],
  define: {
    __VERSION__: JSON.stringify(version),
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "src"),
    },
  },
})

```

**Comment by eidens-design** [comment]
Have you worked this out, yet? I am trying to achieve the same thing.

**Comment by muuvmuuv** [comment]
@eidens-design no, unfortunately not...

**Comment by matthiasott** [comment]
Hey everyone! I have a fix for this ready which I also successfully tested in an Eleventy+Vite project I am working on – should I go ahead and create a PR or would you like to discuss/review the solution first, @khalwat?
It basically just checks if the `inline` option is set to true and if so, the target will be HTML instead of CSS:
https://github.com/nystudio107/rollup-plugin-critical/compare/master...matthiasott:inline-support-fix

**Comment by khalwat** [comment]
Go ahead and create the PR @matthiasott -- much appreciated!

**Comment by anon36** [comment]
@matthiasott Do you have a working example by any chance?

**Comment by khalwat** [comment]
I'm planning to do the PR merge & QA on this tomorrow!

**Comment by khalwat** [comment]
Sorry for the delay; I added tests and published it as 1.0.9:

https://github.com/nystudio107/rollup-plugin-critical/releases/tag/1.0.9

**Comment by khalwat** [comment]
thx for the PR @matthiasott !

**Comment by matthiasott** [comment]
🙌 Anytime!
